uevent_sender: Fix unaligned access and data types
Sync string_hash32() with the original code in systemd: Adjust the
current source path in the comment, and fix the data type to `uint32_t`
as the algorithm (and even the name) already assume 32 bits. Also, the
result is passed into `htonl()` which also expects 32 bits.

Even the original code also causes an unaligned access, seen with clang
and `-Wcast-align`:
```
src/uevent_sender.c:170:20: error: cast from 'const unsigned char *' to 'unsigned int *' increases required alignment from 1 to 4 [-Werror,-Wcast-align]
        unsigned int k = *(unsigned int *)data;
                          ^~~~~~~~~~~~~~~~~~~~
```

Avoid that by using memcpy().