Re-drop -Werror=unused-parameter
It breaks gtk-doc build:
```
mockdev-scan.c: In function ‘output_object_actions’:
umockdev-scan.c:569:30: error: unused parameter ‘fp’ [-Werror=unused-parameter]
  569 | output_object_actions (FILE *fp, GType object_type)
      |                        ~~~~~~^~
cc1: all warnings being treated as errors
```