Fix `ndebug` builds with latest gcc
This slightly changed from the previous `unused-but-set-variable` to
`unused-variable`:

```
../../source/src/libumockdev-preload.c:973:24: error: unused variable 'r' [-Werror=unused-variable]
  973 |                 size_t r = _fwrite(header, strlen(header), 1, srinfo->log);
      |                        ^
```

So don't make that warning fatal either in `ndebug` mode.